name: Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Stylesheet verification
      run: for script in ./.scripts/lint/stylesheet/* ; do $script; done
